# Createing an Array

### np.array(): Converts a standard Python list into a NumPy array.
### np.zeros(): Creates an array completely filled with zeros (great for placeholders) .
### np.arange(): Creates a sequence of numbers, specifying a start, stop, and step (similar to Python's built-in range()).
### np.linspace(): Creates an array of evenly spaced numbers over a specific range. You te ll it how many numbers you want, and it calculates the spacing.

In [30]:
import numpy as np     # so we import this to use library of numpy and i use as to write a short name 

#List → can store different data types (int, string, float, etc.)
#Array → stores only one data type and is usually used for numbers

my_List = [1,2,3,4]
arr1 = np.array(my_List)  # this is convert from form list to array

arr2 = np.zeros(2)    # .zeros

# { ohh in this we can use .zeros() .ones()  1. make a place that we can store memorize 
# 2. we can use .zeros or .ones to calculate  3. we use '0' for (black pixel) and  '1' orr '255' as a white (pixel)    }


# .ones((page, rows, colons))
arr3 = np.ones((1,2,3))   
# arr3 = np.ones(3)   { so this mean that we can use like as row or colon } 

# array1(5)  it is 1D
# array2((2,3)) it is 2D      ->  rows, cols 
# array3((1,2,3))   {  np.zeros((depth, rows, cols)) —> using for RGB color }   


# .full()   like i want have 2 row and 5 colon but fill by 10 
arr4 = np.full((2,5),10)

arr5 = np.arange(10,0,-2) # np.arange(start, stop, step)

arr6 = np.linspace(0,10,5) # .linspace(start,stop,num) we use to make and share is balance 

print(arr1)
print(arr2)
print(arr3)
print(arr4)
print(arr5)
print(arr6)

[1 2 3 4]
[0. 0.]
[[[1. 1. 1.]
  [1. 1. 1.]]]
[[10 10 10 10 10]
 [10 10 10 10 10]]
[10  8  6  4  2]
[ 0.   2.5  5.   7.5 10. ]


# Array Attributes

In [51]:
my_array = np.array([[1,2,3,
                    4,5,6]]) 
print(my_array)
print(my_array.ndim)   # tell what this is in what 'Number of Dimensions'
print(my_array.shape)  # shape tell how much the list item have from start to stop 
print(my_array.size)   # size tell how much item in the list have

# ---> dtype have 2 is Auto and we set 

# this one is Auto
print(my_array.dtype)  #Auto the result is { int64 } 

# we can change the dtype of the array by using like this 
array_Chnage = my_array.astype('int32')
print(array_Chnage.dtype)

# this one we set by my self That we call("Force dtype")
my_array1 = np.array([[1,2,3,
                    4,5,6]], dtype= np.float32) # or int8
print(my_array1.dtype)




[[1 2 3 4 5 6]]
2
(1, 6)
6
int64
int32
float32


# Indexing & slicing 

In [59]:

# array[row_slice, column_slice]

my_array2 = np.array([[1, 2, 3],
                      [4, 5, 6],
                      [7, 8, 9]])


# the select only one it is call an Indexing 
print(my_array2[1,2])  # out put must be 6 becasue i have put that in row 1 and colon 2  [ Note we count from '0' ]
print(my_array2[2,2]) # out put must be 9


# this print it is call slicing  so we need to use 2[] + :
print(my_array2[:3])
print(my_array2[1:3, 0:2])
                # this is a row that we use 1:3 and 0:2 is a colon that we need to slicing form index 0 to 1 so it mean 4,5 

6
9
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[4 5]
 [7 8]]


# Boolean Indexing (Masking)

In [69]:
# Boolean Indexing (Masking)

# we use to filtering data by using true/false condition. It is a smart filtering faster and easy one to filtering  the data 
arr6 = np.array([10, 15, 20, 25, 30, 35, 40, 45 ,50, 60])
mask = arr6 >= 20     # ohh so it mean that on this we need to use an operator condition to see True/False
print(mask)

# this is how we filtering only the Ture out
filtered_arr = arr6[mask]
print(filtered_arr)

# we can also filtering only teh false also 
print(arr6[~mask])

# > < != == >= <=

# or we can use the filtering derictly also 
print(arr6[arr6 > 20])
print(arr6[arr6 < 20])

[False False  True  True  True  True  True  True  True  True]
[20 25 30 35 40 45 50 60]
[10 15]
[25 30 35 40 45 50 60]
[10 15]


# Reshaping

In [77]:
# this concept is talking about how can we do we do this Array that have one line change to 2 row without the actual numbers inside.

import numpy as np

# like this we have 1 array list so we can chnage
arr7 = np.array([1,2,3,4,5,6,])

change = arr7.reshape(2,3)    # key word is '.reshape'

print(change)


# we use .flatten() or .ravel() to make a D2 or D3 back to D1 by using those 2 build-in method 

matrix = np.array([[1, 2, 3], 
                   [4, 5, 6]])

print(matrix)

# so we use to convert to D1 that have only one line
ToD1 = matrix.ravel()   ## or  .flatten()
print(ToD1)

[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


# Vectorized Operations

In [82]:
# we use this to calculate array at the same thing without using loop to calculate again and again 

# it is fast and can make less error 

# so this can use only in the same index or the same level only [like D1 or D2 or D3]if one index os longer or bigger than cannot calculate 

a = np.array([1,2,3])
b = np.array([4,5,6])

result = a + b

print(result)

[5 7 9]
[ 3  4  5  6  7  8  9 10]


# Broadcasting

In [83]:
# it is the specail ability of numpy that allow to use us can calculate with other array that we are not in the simalarly level

# like we can calculate D1 with D2 or D3 like that 

# the important is broadcasting is forcuse on give the number that we want to add in to all the index on the list

ab = np.array([1,2,3,4,5,6,7,8])
result2 = ab + 2
print(result2)

a = np.array([1,2,3])
b = np.array(10)
print(a+b) 

[ 3  4  5  6  7  8  9 10]
[11 12 13]


# Universal Functions (ufuncs)



In [84]:
# it is a build-in method that we can use beacuse it is have math Formula (element-by-element) in array

# np.add() np.subtract() np.multiply() np.divide() np.sqrt() np.sin() , np.cos()

arr9 = np.array([1, 4, 9, 16])
result_arr9 = np.sqrt(arr9)
print(result_arr9)

arr10 = np.array([12,13,14,15])
result_arr10 = np.sin(arr10)
print(result_arr10)

[1. 2. 3. 4.]
[-0.53657292  0.42016704  0.99060736  0.65028784]


# Aggregations

In [86]:
# we use this to calculate an array list from alot of number to summary have only one

#np.sum() → sum all the number in array
#np.mean() → (average)
#np.median() → the middle of the number
#np.min() → the smallest number
#np.max() → the biggest number
#np.std() → This is the most common one. It tells you: "On average, how far is each number from the middle just Standard Deviation squared ($std^2$).
#np.var() → just Standard Deviation squared (std^2).


import numpy as np

city_a = [24, 25, 26, 25, 25]
city_b = [10, 25, 40, 20, 30]

# Standard Deviation (The easy-to-read gap)
print(np.std(city_a))  # Output: 0.63     # how far from the middle one
print(np.var(city_a))   # var us mean 0.63 x 0.63 so the result is 4

print(np.std(city_b))  # Output: 10.0

0.6324555320336759
0.4
10.0


# Axis (x,y) 

In [18]:
# so we use this to calculete the Axis x or y 
import numpy as np

# axis=0, the operation moves down through the rows.
# axis=1, The biggest value in each column (top to bottom).
#axis=2, The biggest value in each row (left to right).

# so the axis how we use it is depend on (Dimensions) how much the data of you use 

data_3d = np.ones((1, 2, 4)) 

result_axis2 = data_3d.sum(axis=2)

print(data_3d)

print(f"Original Shape: {data_3d.shape}")
print(f"Shape after axis=2 sum: {result_axis2.shape}")
print(result_axis2)


[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]]]
Original Shape: (1, 2, 4)
Shape after axis=2 sum: (1, 2)
[[4. 4.]]
