# **Numpy**



*   np.array(): Converts a standard Python list into a NumPy array.
*   np.zeros(): Creates an array completely filled with zeros (great for placeholders).
*   np.ones(): Creates an array completely filled with ones.
*   np.arange(): Creates a sequence of numbers, specifying a start, stop, and step (similar to Python's built-in range()).
*   np.linspace(): Creates an array of evenly spaced numbers over a specific range. You tell it how many numbers you want, and it calculates the spacing.

In [ ]:
## Creating arrays

import numpy as np
# import numpy

# create frome a list
my_list = [1,2,3]
arr1 = np.array(my_list)

arr2 = np.zeros(5)
# create 2 x 3 grids of ones
arr3 = np.ones((2,3))

arr4 = np.arange(0,10,2)

arr5 = np.linspace(0, 1, 5)

In [ ]:
print(arr1)
print(arr2)
print(arr3)
print(arr4)
print(arr5)

[1 2 3]
[0. 0. 0. 0. 0.]
[[1. 1. 1.]
 [1. 1. 1.]]
[0 2 4 6 8]
[0.   0.25 0.5  0.75 1.  ]


Array Attributes

*   ndim: Tells you the number of dimensions (e.g., 1 for a flat list, 2 for a grid/matrix, 3 for a cube).
*   shape: Returns a tuple showing the exact length of the array along each dimension (like rows and columns).
*   size: Tells you the total number of individual elements packed inside the array.
*   dtype: Tells you what specific kind of data is stored inside (e.g., integers, floats).

Data Types and Memory

*   int32 / int64: Whole numbers. 64-bit allows for larger numbers but uses twice the memory of 32-bit.
*   float32 / float64: Decimal numbers.

In [ ]:
# 2D array which contain 2-rows and 2-columns

my_array = np.array([[1,2,3],
                     [4,5,6]], dtype=np.int8)

In [ ]:
print(my_array)
print(my_array.ndim)
print(my_array.shape)
print(my_array.dtype)

[[1 2 3]
 [4 5 6]]
2
(2, 3)
int8


Basic Indexing & Slicing

- Indexing is picking a single element (like picking a specific house on a street).
- Slicing is grabbing a range of elements using the colon : symbol (like selecting a whole block of houses). The format is start:stop.
- For 2D arrays (like a spreadsheet), you use a comma to separate rows and columns: array[row_slice, column_slice].

In [ ]:
# Indexing & slicing

# create a 2-D array (3-rows and 3-columns)
my_array2 = np.array([[1, 2, 3],
                      [4, 5, 6],
                      [7, 8, 9]])

In [ ]:
# print(my_array2)
print(my_array2[1, 2])

# array[row_slice, column_slice]
print(my_array2[1:3, 0:2])

6
[[4 5]
 [7 8]]


Boolean Indexing (Masking)

Filtering data using a True/False condition. Instead of asking for data by its position, you ask for data based on its value. It creates an invisible "mask" over your array, hiding the data that doesn't match your rule and keeping only the data that does.

In [ ]:
# boolean indexing (masking)

arr6 = np.array([10, 15, 20, 25, 30])
mask = arr6 >= 20
print(mask)

[False False  True  True  True]


In [ ]:
# filtering
mask_filtering = arr6[mask]
print(mask_filtering)

[20 25 30]


In [ ]:
print(arr6[arr6 >= 20])

[20 25 30]


Reshaping

Changing the physical layout (dimensions) of your data without changing the actual numbers inside.
- .reshape(rows, columns): Turns a flat list into a grid, or changes the shape of a grid (e.g., turning a 1x6 line into a 2x3 grid). Note: The total number of elements must stay the exact same.
- .flatten() or .ravel(): Does the exact opposite. It takes a multi-dimensional grid and squashes it completely flat into a 1D line.

In [ ]:
arr7 = np.array([1,2,3,4,5,6])
grid_arr7 = arr7.reshape(3,2)

In [ ]:
print(grid_arr7)

[[1 2]
 [3 4]
 [5 6]]


In [ ]:
flatten_arr7 = grid_arr7.flatten()
flatten2_arr7 = grid_arr7.ravel()
print(arr7)
print(flatten_arr7)
print(flatten2_arr7)

[1 2 3 4 5 6]
[1 2 3 4 5 6]
[1 2 3 4 5 6]


Vectorized Operations

Vectorization means applying an operation to an entire array at once, rather than writing a for loop to process each item one by one. Behind the scenes, NumPy handles the looping in highly optimized C code, making it incredibly fast.

In [ ]:
# Vectorized Operations

a = np.array([1,2,3])
b = np.array([4,5,6])

result = a + b

In [ ]:
print(result)

[5 7 9]


Broadcasting Rules

Broadcasting is a set of rules NumPy uses to perform operations on arrays that have different shapes. Instead of throwing an error, NumPy virtually "stretches" (or broadcasts) the smaller array across the larger one so their shapes match.

In [ ]:
# broadcasting rules
arr8 = np.array([
    [1, 2, 3],
    [4, 5, 6]
    ])
result_arr8 = arr8 + 10
print(result_arr8)

[[11 12 13]
 [14 15 16]]


Universal Functions (ufuncs)

Universal functions are built-in mathematical functions in NumPy that are specifically designed to operate element-by-element on arrays. They support vectorization and broadcasting out of the box, making complex math operations extremely fast.

In [ ]:
# universal function (ufuncs)
arr9 = np.array([1, 4, 9, 16])
result_arr9 = np.sqrt(arr9)
print(result_arr9)

[1. 2. 3. 4.]


Aggregations (The "What")
Aggregations are functions that take a bunch of numbers in an array and boil them down to a single summary value.
- np.sum(): Adds all the numbers together.
- np.mean(): Calculates the average.
- np.median(): Finds the exact middle value (if you lined all the numbers up in order).
- np.min() & np.max(): Finds the smallest and largest numbers, respectively.
- np.std(): Calculates the standard deviation (measures how spread out your numbers are from the average).
- np.var(): Calculates the variance (the standard deviation squared).

Axis Operations (The "Where")
By default, aggregation functions apply to the entire array. However, if you have a 2D array (like a spreadsheet with rows and columns), you often want to calculate statistics for specific rows or columns. You do this by defining the axis.
- axis=0 (Vertical): The operation travels down the rows. It calculates a result for each column.
- axis=1 (Horizontal): The operation travels across the columns. It calculates a result for each row.

In [ ]:
# aggregation and axis operation

import numpy as np

data = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

print("Total Sum:", np.sum(data))
print("Maximum Value:", np.max(data))

print("Column Sums (axis=0):", np.sum(data, axis=0))
print("Row Sums (axis=1):", np.sum(data, axis=1))

Total Sum: 21
Maximum Value: 6
Column Sums (axis=0): [5 7 9]
Row Sums (axis=1): [ 6 15]
